#+TITLE: Colophon
#+SLUG:colophon
#+OPTIONS: num:nil toc:nil

Ce site statique est généré à l'aide d'un moteur de blog basé sur Emacs, [[https://emacs.love/weblorg/][/weblorg/]]. Ce moteur de blog permet d'écrire avec le language ~org~ (que je trouve bien supérieur au markdown). J'utilise un [[https://github.com/MBunel/mbunel.xyz/tree/main/theme][template personnalisé]],
basé sur les polices [[https://github.com/impallari/Libre-Baskerville][Libre Baskerville]], [[https://github.com/impallari/Libre-Franklin][Libre Franklin]], [[https://github.com/googlefonts/spacemono][Space Mono]] (toutes ces polices sont sous licence [[https://openfontlicense.org/open-font-license-official-text/][OFL v1.1]]) et
la palette de couleurs [[https://catppuccin.com/][Catppuccin]] (licence [[https://directory.fsf.org/wiki/License:Expat][MIT]]).

La publication de ce site est automatisée par une [[https://github.com/MBunel/mbunel.xyz/blob/main/.github/workflows/main.yml][action GitHub]] reproductible, grâce à l'utilisation du gestionnaire de paquets fonctionnel [[https://guix.gnu.org/][Guix]].

Guix permet de définir et de reproduire un environnent logiciel donné, incluant les logiciels ainsi que l'ensemble de leurs dépendances. Ce (gros) [[url_for:static,file=images/dep_graph.svg][fichier svg]] présente le graphe complet des dépendances de ce site. Il est généré automatiquement, à chaque génération de ce site, avec la commande suivante :

#+LABEL: dep_graph
#+BEGIN_SRC shell :exports both :results raw :wrap src dot
guix graph -t references $(readlink -f $GUIX_ENVIRONMENT/)
#+END_SRC

#+HEADER: :file ../../_temp/static/images/dep_graph.svg :results none
#+RESULTS: dep_graph

Le gestionnaire de paquets [[https://guix.gnu.org/][Guix]] permet de reproduire cet état du système sur différentes machines, garantissant la reproductibilté de ce site. On peut retourner à cet état précis en utilisant la commande suivante :

#+BEGIN_SRC shell :eval no
guix time-machine -m manifest.scm -c channels.scm -- shell
#+END_SRC

Avec ~manifest.scm~ le fichier suivant :

#+INCLUDE: "../../manifest.scm" src scheme :eval no

et ~channels.scm~ le fichier suivant :

#+INCLUDE: "../../channels.scm" src scheme :eval no

Les sources sont disponibles sur le dépôt Github [[https://github.com/MBunel/mbunel.xyz][MBunel/mbunel.xyz]].

Les diverses modifications effectuées sont listées dans la page [[url_for:pages,slug=log][log]].
